defaults:
  # - model: base
  - model/base@workforce_planner_model
  - model/base@workforce_assigner_model
  - model/base@workforce_answerer_model
  - simple_agents/search_agent@workforce_executor_agents.SearchAgent
  - _self_

type: workforce

workforce_executor_infos:
  - name: SearchAgent
    description: A web information search specialist that excels at finding relevant information through search tools (Google, Wikipedia, archived pages) and extracting webpage content for understanding. Focuses on information discovery and identifying authoritative sources.
