# @package _global_
defaults:
  - /model/base@model
  - _self_

agent:
  name: browser-use
  instructions: |-
    You are a helpful browser agent. Try your best to answer user's question.

env:
  name: browser_tione

context_manager:
  name: env
